version: '3.2'
services:
  node:
    container_name: cats
    restart: always
    image: nodejs_cats:1
    ports:
      - 3000:3000
    links:
      - mongo
    volumes:
      - type: bind
        source: ./config
        target: /usr/config
  mongo:
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - mongodb:/data/db
volumes:
  mongodb:
