version: '3.2'
services:
  proxy:
    container_name: proxy
    restart: always
    build: nginx/.
    # image: proxy:1
    ports:
      - 8080:8080
    links:
      - nodejs-catsapp
  nodejs-catsapp:
    container_name: nodejs-catsapp
    restart: always
    build: .
    # image: nodejs_cats:1
    ports:
      - 3000:3000
    links:
      - mongo
    volumes:
      - type: bind
        source: ./config
        target: /usr/config
  mongo:
    container_name: mongo
    image: mongo:5.0.3
    ports:
      - 27017:27017
    volumes:
      - mongodb:/data/db
volumes:
  mongodb:
