apiVersion: v1
kind: Service
metadata:
  name: mongo-db
  labels:
    app: mongo-db
spec:
  ports:
    - port: {{ index .Values "mongo-db" "service" "port" }}
      protocol: TCP
      targetPort: {{ index .Values "mongo-db" "service" "port" }}
  clusterIP: None
  selector:
    app: mongo-db
  sessionAffinity: None
  type: ClusterIP
