apiVersion: v1
kind: Service
metadata:
  name: nginx-proxy
  labels:
    app: nginx-proxy
spec:
  ports:
    - name: nginx-proxy
      port: {{ index .Values "nginx-proxy" "service" "port" }}
      protocol: TCP
      targetPort: {{ index .Values "nginx-proxy" "service" "port" }}
  selector:
    app: nginx-proxy
  sessionAffinity: None
  type: ClusterIP
