apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nginx-proxy
  labels:
    app: nginx-proxy
spec:
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: nginx-proxy
            port:
              number: {{ index .Values "nginx-proxy" "service" "port" }}
