apiVersion: v1
kind: ConfigMap
metadata:
  name: nodejs-catsapp
  labels:
    app: nodejs-catsapp
data:
    default.json:  |-
      {
          "containerPort": {{ index .Values "nodejs-catsapp" "service" "port" }},
          "Cats": {
              "dbConfig": {
                  "host": "mongo-db-0.mongo-db,mongo-db-1.mongo-db,mongo-db-2.mongo-db",
                  "port": {{ index .Values "mongo-db" "service" "port" }},
                  "dbName": "test"
              }
          }
      }
